"use client";

// /bench — public token-efficiency scoreboard.
//
// Reads the static JSON file at `/bench/scoreboard.json` (committed
// in-repo at `web/public/bench/scoreboard.json`). The file is
// produced by `crates/nexus-eval/token_bench::aggregate`; CI
// regenerates it on every push. Rendering it client-side means the
// page is dead-simple, static, and provably matches the current
// suite version.

import { useEffect, useState } from "react";

interface CandidateRow {
  candidate: string;
  tasks_attempted: number;
  median_total_tokens: number;
  p95_total_tokens: number;
  median_cost_usd: number;
  mean_quality: number | null;
}

interface ScoreboardRun {
  ran_at: string;
  suite_version: string;
  tasks_total: number;
  rows: CandidateRow[];
  note?: string;
}

export default function BenchPage() {
  const [data, setData] = useState<ScoreboardRun | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    fetch("/bench/scoreboard.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<ScoreboardRun>;
      })
      .then(setData)
      .catch((e) => setErr(e instanceof Error ? e.message : String(e)));
  }, []);

  const headlineRatio = ratioVsBaseline(data);

  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-100 p-8">
      <div className="mx-auto max-w-3xl space-y-6">
        <header>
          <h1 className="text-2xl font-semibold tracking-tight">
            Nexus Token-Efficiency Benchmark
          </h1>
          <p className="mt-1 text-sm text-neutral-400">
            Reproducible comparison: how many tokens each candidate
            system uses on the same frozen suite of coding tasks.
            Suite lives at{" "}
            <code className="rounded bg-neutral-800 px-1.5 py-0.5 text-xs">
              crates/nexus-eval/benchmarks/v1/*.json
            </code>
            ; the scoreboard is regenerated by CI.
          </p>
        </header>

        {err && (
          <div className="rounded-lg border border-red-900/60 bg-red-950/40 p-4 text-sm text-red-200">
            {err}
          </div>
        )}

        {data && (
          <>
            <div className="flex items-baseline gap-6">
              <dl>
                <dt className="text-xs text-neutral-400">Suite</dt>
                <dd className="font-mono text-sm">{data.suite_version}</dd>
              </dl>
              <dl>
                <dt className="text-xs text-neutral-400">Tasks</dt>
                <dd className="font-mono text-sm">{data.tasks_total}</dd>
              </dl>
              <dl>
                <dt className="text-xs text-neutral-400">Last run</dt>
                <dd className="font-mono text-sm">
                  {new Date(data.ran_at).toLocaleString()}
                </dd>
              </dl>
              {headlineRatio && (
                <dl>
                  <dt className="text-xs text-neutral-400">
                    Token ratio
                  </dt>
                  <dd className="text-base font-semibold text-emerald-300">
                    {headlineRatio.toFixed(2)}× fewer than baseline
                  </dd>
                </dl>
              )}
            </div>

            {data.rows.length === 0 ? (
              <div className="rounded-lg border border-amber-900/60 bg-amber-950/30 p-4 text-sm text-amber-200">
                {data.note ??
                  "Scoreboard has no rows yet. Run the benchmark to populate."}
              </div>
            ) : (
              <table className="w-full border-collapse text-sm">
                <thead>
                  <tr className="border-b border-neutral-800 text-left text-xs text-neutral-400">
                    <th className="py-2">Candidate</th>
                    <th>Tasks</th>
                    <th>Median tokens</th>
                    <th>P95 tokens</th>
                    <th>Median $ / task</th>
                    <th>Mean quality</th>
                  </tr>
                </thead>
                <tbody>
                  {data.rows.map((row, i) => (
                    <tr
                      key={row.candidate}
                      className={
                        i === 0
                          ? "bg-emerald-950/30 font-semibold text-emerald-200"
                          : "text-neutral-200"
                      }
                    >
                      <td className="py-2">{row.candidate}</td>
                      <td>{row.tasks_attempted}</td>
                      <td className="font-mono">
                        {row.median_total_tokens.toLocaleString()}
                      </td>
                      <td className="font-mono">
                        {row.p95_total_tokens.toLocaleString()}
                      </td>
                      <td className="font-mono">
                        ${row.median_cost_usd.toFixed(4)}
                      </td>
                      <td className="font-mono">
                        {row.mean_quality == null
                          ? "—"
                          : row.mean_quality.toFixed(2)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </>
        )}
      </div>
    </div>
  );
}

function ratioVsBaseline(data: ScoreboardRun | null): number | null {
  if (!data || data.rows.length < 2) return null;
  const nexus = data.rows.find((r) =>
    r.candidate.toLowerCase().includes("nexus"),
  );
  const baseline = data.rows.find(
    (r) => !r.candidate.toLowerCase().includes("nexus"),
  );
  if (!nexus || !baseline || nexus.median_total_tokens === 0) return null;
  return baseline.median_total_tokens / nexus.median_total_tokens;
}
