//! Pipeline Turbo — parallel LLM execution, seed data generation,
//! retry with backoff, and smart model routing for the execution pipeline.
//!
//! This module provides acceleration functions that the execution pipeline
//! calls to run independent LLM steps concurrently and populate generated
//! apps with real data.

use std::sync::Arc;
use std::time::Duration;

use serde_json::Value;
use tokio::sync::mpsc;
use tracing::{info, warn};

use crate::execution_pipeline::PipelineEvent;
use crate::intent_engine::FlatIntent;
use crate::product_engine::ProductBrief;
use crate::state::AppState;

// ---------------------------------------------------------------------------
// 1. Parallel LLM Generation
// ---------------------------------------------------------------------------

/// Result of a parallel generation phase.
#[derive(Debug)]
pub struct ParallelGenResult {
    /// Files generated by each parallel step: (step_name, vec of (path, content))
    pub files: Vec<(String, Vec<(String, String)>)>,
    /// Steps that failed
    pub failures: Vec<(String, String)>,
    /// Total wall-clock time
    pub duration_ms: u64,
}

/// Run multiple LLM generation steps in parallel.
/// Returns all generated files from all steps.
///
/// Steps that fail are recorded but don't block other steps.
pub async fn run_parallel_generation(
    app: &Arc<AppState>,
    project_id: &str,
    prompts: Vec<(String, String)>, // (step_name, prompt)
    tx: &mpsc::Sender<PipelineEvent>,
) -> ParallelGenResult {
    let start = std::time::Instant::now();
    let mut handles = Vec::new();

    for (step_name, prompt) in prompts {
        let app_clone = app.clone();
        let pid = project_id.to_string();
        let sname = step_name.clone();
        let tx_clone = tx.clone();

        let handle = tokio::spawn(async move {
            let _ = tx_clone.send(PipelineEvent::Step {
                index: 0,
                name: sname.clone(),
                status: "running".into(),
                detail: format!("Generating {} (parallel)...", sname),
                duration_ms: None,
            }).await;

            let step_start = std::time::Instant::now();
            let result = call_with_retry(&app_clone, &pid, &prompt, 2).await;
            let dur = step_start.elapsed().as_millis() as u64;

            match result {
                Ok(response) => {
                    let files = nexus_store::parse_file_blocks(&response);
                    let _ = tx_clone.send(PipelineEvent::Step {
                        index: 0,
                        name: sname.clone(),
                        status: "completed".into(),
                        detail: format!("{} files generated in {}ms", files.len(), dur),
                        duration_ms: Some(dur),
                    }).await;
                    Ok((sname, files))
                }
                Err(e) => {
                    let _ = tx_clone.send(PipelineEvent::Step {
                        index: 0,
                        name: sname.clone(),
                        status: "failed".into(),
                        detail: e.clone(),
                        duration_ms: Some(dur),
                    }).await;
                    Err((sname, e))
                }
            }
        });

        handles.push(handle);
    }

    let mut files = Vec::new();
    let mut failures = Vec::new();

    for handle in handles {
        match handle.await {
            Ok(Ok((name, step_files))) => {
                files.push((name, step_files));
            }
            Ok(Err((name, error))) => {
                failures.push((name, error));
            }
            Err(e) => {
                failures.push(("unknown".into(), format!("Task panicked: {}", e)));
            }
        }
    }

    let duration_ms = start.elapsed().as_millis() as u64;

    info!(
        parallel_steps = files.len() + failures.len(),
        succeeded = files.len(),
        failed = failures.len(),
        duration_ms = duration_ms,
        "Parallel generation complete"
    );

    ParallelGenResult {
        files,
        failures,
        duration_ms,
    }
}

// ---------------------------------------------------------------------------
// 2. Retry with Exponential Backoff
// ---------------------------------------------------------------------------

/// Call the LLM with retry logic. Retries on failure with exponential backoff.
pub async fn call_with_retry(
    app: &Arc<AppState>,
    project_id: &str,
    prompt: &str,
    max_retries: u32,
) -> Result<String, String> {
    let mut last_error = String::new();

    for attempt in 0..=max_retries {
        if attempt > 0 {
            let delay = Duration::from_millis(500 * 2u64.pow(attempt - 1));
            warn!(attempt = attempt, delay_ms = delay.as_millis(), "Retrying LLM call");
            tokio::time::sleep(delay).await;
        }

        match crate::handlers::chat::call_llm_simple_for_project(
            app,
            prompt,
            Some(project_id),
        )
        .await
        {
            Ok(response) => {
                // Validate response has actual content
                let trimmed = response.trim();
                if trimmed.is_empty() || trimmed.len() < 50 {
                    last_error = "LLM returned empty or very short response".into();
                    continue;
                }
                return Ok(response);
            }
            Err(e) => {
                last_error = e.to_string();
            }
        }
    }

    Err(format!("Failed after {} retries: {}", max_retries + 1, last_error))
}

// ---------------------------------------------------------------------------
// 3. Seed Data SQL Generator
// ---------------------------------------------------------------------------

/// Generate SQL INSERT statements to populate the database with realistic seed data
/// from the product brief.
pub fn generate_seed_sql(brief: &ProductBrief, spec: &Value) -> String {
    let mut sql = String::from("-- Seed data generated by Nexus Product Engine\n\n");

    let entities = spec.get("entities")
        .and_then(|e| e.as_array())
        .cloned()
        .unwrap_or_default();

    for section in &brief.seed_content {
        // Try to match section to an entity
        let entity = find_matching_entity(&section.section_id, &section.title, &entities);
        let Some(entity) = entity else { continue };

        let entity_name = entity.get("name").and_then(|n| n.as_str()).unwrap_or("items");
        let fields = entity.get("fields")
            .and_then(|f| f.as_array())
            .cloned()
            .unwrap_or_default();

        let field_names: Vec<String> = fields.iter()
            .filter_map(|f| f.get("name").and_then(|n| n.as_str()))
            .filter(|n| *n != "id" && *n != "created_at")
            .map(String::from)
            .collect();

        if field_names.is_empty() { continue; }

        sql.push_str(&format!("-- {} seed data\n", entity_name));

        for item in &section.items {
            let id = uuid::Uuid::new_v4().to_string();

            // Map content item fields to entity fields
            let mut values: Vec<String> = Vec::new();
            let mut columns: Vec<String> = vec!["id".into()];
            values.push(format!("'{}'", id));

            for field_name in &field_names {
                let lower = field_name.to_lowercase();
                let val = if lower.contains("name") || lower.contains("title") {
                    Some(item.name.clone())
                } else if lower.contains("desc") || lower.contains("summary") || lower.contains("detail") {
                    Some(item.description.clone())
                } else if lower.contains("price") || lower.contains("cost") || lower.contains("amount") {
                    item.price.as_ref().map(|p| p.replace('$', "").replace("/mo", "").replace("/night", ""))
                } else if lower.contains("category") || lower.contains("type") || lower.contains("region") {
                    Some(item.detail.clone())
                } else if lower.contains("badge") || lower.contains("tag") || lower.contains("label") {
                    item.badge.clone()
                } else if lower.contains("image") || lower.contains("icon") || lower.contains("emoji") {
                    Some(item.image_emoji.clone())
                } else {
                    None
                };

                if let Some(v) = val {
                    columns.push(field_name.clone());
                    values.push(format!("'{}'", v.replace('\'', "''")));
                }
            }

            sql.push_str(&format!(
                "INSERT OR IGNORE INTO {} ({}) VALUES ({});\n",
                entity_name,
                columns.join(", "),
                values.join(", "),
            ));
        }

        sql.push('\n');
    }

    sql
}

/// Try to match a content section to a database entity.
fn find_matching_entity<'a>(section_id: &str, section_title: &str, entities: &'a [Value]) -> Option<&'a Value> {
    let lower_id = section_id.to_lowercase();
    let lower_title = section_title.to_lowercase();

    for entity in entities {
        let name = entity.get("name").and_then(|n| n.as_str()).unwrap_or("").to_lowercase();

        // Direct name match
        if name == lower_id || lower_id.contains(&name) || name.contains(&lower_id) {
            return Some(entity);
        }

        // Singular/plural match: "categories" matches "category", "wines" matches "wine"
        let name_singular = name.trim_end_matches('s');
        let id_singular = lower_id.trim_end_matches("ies").to_string() + if lower_id.ends_with("ies") { "y" } else { "" };
        let id_singular = if id_singular == lower_id { lower_id.trim_end_matches('s').to_string() } else { id_singular };
        if name_singular == id_singular || name == id_singular || name_singular == lower_id {
            return Some(entity);
        }

        // Title-based match
        if lower_title.contains(&name) {
            return Some(entity);
        }
    }

    // Fallback: match common section IDs to first entity
    if matches!(lower_id.as_str(), "featured" | "products" | "listings" | "menu" | "programs") {
        return entities.first();
    }

    None
}

/// Generate a seed data script that runs on app startup.
pub fn generate_seed_script(seed_sql: &str) -> String {
    if seed_sql.trim().is_empty() || seed_sql.lines().all(|l| l.starts_with("--") || l.trim().is_empty()) {
        return String::new();
    }

    format!(
        r#"import {{ getDb }} from './index';

// Seed the database with sample data on first run
export function seedDatabase() {{
  const db = getDb();
  const count = db.prepare('SELECT COUNT(*) as c FROM sqlite_master WHERE type="table"').get() as {{ c: number }};
  if (count.c === 0) return; // No tables yet

  // Check if already seeded
  try {{
    const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all() as {{ name: string }}[];
    for (const table of tables) {{
      const rowCount = db.prepare(`SELECT COUNT(*) as c FROM ${{table.name}}`).get() as {{ c: number }};
      if (rowCount.c > 0) return; // Already has data
    }}
  }} catch {{
    return;
  }}

  // Insert seed data
  db.exec(`
{seed_sql}  `);

  console.log('Database seeded with sample data');
}}

// Auto-seed on import
seedDatabase();
"#
    )
}

// ---------------------------------------------------------------------------
// 4. Smart Model Routing
// ---------------------------------------------------------------------------

/// Select the best model for a pipeline step based on complexity and purpose.
pub fn route_model_for_step(step: &str, _intent: &FlatIntent) -> &'static str {
    match step {
        // Strong model for spec generation (most critical — shapes everything)
        "generate_spec" => "gpt-4.1",
        // Strong model for UI (user-facing quality matters most)
        "generate_ui" => "gpt-4.1",
        // Medium model for API routes (structured, less creative)
        "generate_api" => "gpt-4.1-mini",
        // Medium model for auth (boilerplate-heavy)
        "generate_auth" => "gpt-4.1-mini",
        // Cheap model for validation (yes/no decisions)
        "validate_spec" => "gpt-4.1-mini",
        // Default
        _ => "gpt-4.1",
    }
}

// ---------------------------------------------------------------------------
// 5. Health Check
// ---------------------------------------------------------------------------

/// Wait for a dev server to become healthy, with timeout.
pub async fn wait_for_health(port: u32, timeout_secs: u64) -> bool {
    let url = format!("http://localhost:{}", port);
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(3))
        .build()
        .unwrap_or_default();

    let deadline = std::time::Instant::now() + Duration::from_secs(timeout_secs);

    while std::time::Instant::now() < deadline {
        match client.get(&url).send().await {
            Ok(resp) if resp.status().is_success() || resp.status().as_u16() == 404 => {
                // 404 is OK — Next.js is running but maybe no root page yet
                info!(port = port, "App health check passed");
                return true;
            }
            _ => {
                tokio::time::sleep(Duration::from_secs(2)).await;
            }
        }
    }

    warn!(port = port, "App health check timed out");
    false
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn seed_sql_generates_inserts() {
        let brief = crate::product_engine::generate_product_brief(
            &crate::intent_engine::analyze_flat("wine marketplace"),
            "wine marketplace",
        );

        let spec = json!({
            "entities": [{
                "name": "Wine",
                "fields": [
                    {"name": "id", "type": "TEXT"},
                    {"name": "name", "type": "TEXT"},
                    {"name": "description", "type": "TEXT"},
                    {"name": "price", "type": "REAL"},
                    {"name": "region", "type": "TEXT"},
                ]
            }]
        });

        let sql = generate_seed_sql(&brief, &spec);
        assert!(sql.contains("INSERT OR IGNORE INTO Wine"));
        assert!(sql.contains("Chateau Margaux"));
        assert!(sql.contains("Opus One"));
    }

    #[test]
    fn seed_script_checks_for_existing_data() {
        let script = generate_seed_script("INSERT INTO wines (id, name) VALUES ('1', 'Test');");
        assert!(script.contains("SELECT COUNT(*)"));
        assert!(script.contains("Already has data"));
    }

    #[test]
    fn model_routing_uses_strong_for_ui() {
        let intent = crate::intent_engine::analyze_flat("wine app");
        assert_eq!(route_model_for_step("generate_ui", &intent), "gpt-4.1");
        assert_eq!(route_model_for_step("generate_api", &intent), "gpt-4.1-mini");
    }

    #[test]
    fn entity_matching_works() {
        let entities = vec![
            json!({"name": "Wine", "fields": [{"name": "id"}, {"name": "name"}]}),
            json!({"name": "Category", "fields": [{"name": "id"}, {"name": "title"}]}),
        ];
        assert!(find_matching_entity("featured", "Featured Collection", &entities).is_some());
        assert!(find_matching_entity("categories", "Explore by Region", &entities).is_some());
    }
}
