//! Code generation HTTP handlers.
//!
//! Every app must be generated by the LLM. No static fallbacks — a template
//! knows nothing about the user's specific requirements.

use std::sync::Arc;

use axum::{
    extract::{Path, State},
    Json,
};
use serde::Deserialize;
use tracing::info;

use nexus_store::{build_generation_prompt, CodeGenMaterializer};

use crate::error::{ApiError, ApiResult};
use crate::security::auth::AuthContext;
use crate::security::tenant::validate_project_access;
use crate::state::AppState;

#[derive(Deserialize)]
pub struct CodeGenInput {
    pub ir: serde_json::Value,
}

/// POST /projects/:id/codegen/plan
pub async fn create_plan(
    State(state): State<Arc<AppState>>,
    auth: AuthContext,
    Path(project_id): Path<String>,
    Json(input): Json<CodeGenInput>,
) -> ApiResult<Json<serde_json::Value>> {
    let db = state.db.lock().await;
    validate_project_access(&db, &project_id, &auth.tenant_id).map_err(ApiError::Forbidden)?;
    let materializer = CodeGenMaterializer::new(&db);
    let plan = materializer
        .plan(&project_id, &input.ir)
        .map_err(|e| ApiError::Internal(format!("Codegen plan failed: {e}")))?;
    Ok(Json(serde_json::to_value(plan)?))
}

#[derive(Deserialize)]
pub struct CodeGenExecuteInput {
    pub ir: serde_json::Value,
    #[serde(default)]
    pub summary: Option<String>,
}

/// POST /projects/:id/codegen/generate
///
/// LLM-powered generation with reformat retries. Never falls back to static
/// templates — those produce apps that have nothing to do with the user's intent.
pub async fn generate(
    State(state): State<Arc<AppState>>,
    auth: AuthContext,
    Path(project_id): Path<String>,
    Json(input): Json<CodeGenExecuteInput>,
) -> ApiResult<Json<serde_json::Value>> {
    let output_dir = state
        .data_dir
        .join("projects")
        .join(&project_id)
        .join("generated");
    let project_data_db = state.project_data_db(&project_id);

    // Step 1: Build plan (needs DB lock, released immediately after)
    let plan = {
        let db = state.db.lock().await;
        validate_project_access(&db, &project_id, &auth.tenant_id).map_err(ApiError::Forbidden)?;
        let materializer = CodeGenMaterializer::new(&db);
        materializer
            .plan(&project_id, &input.ir)
            .map_err(|e| ApiError::Internal(format!("Codegen plan failed: {e}")))?
    };

    // Per-tenant fair-share: a single tenant cannot saturate the global
    // generation queue for everyone behind a shared egress IP.
    if let Err(reason) = state
        .tenant_rate_limiter
        .check(&auth.tenant_id, "generation")
    {
        return Err(ApiError::TooManyRequests(reason));
    }

    // Reserve a global LLM concurrency slot before any LLM IO. The guard is
    // dropped automatically when this function returns, freeing the slot.
    let _llm_slot = state
        .rate_limiter
        .acquire_llm_slot()
        .await
        .map_err(|e| ApiError::TooManyRequests(format!("generation queue is full: {e}")))?;

    // Step 2: LLM generation with retry + reformat
    let summary = input
        .summary
        .as_deref()
        .unwrap_or("A full-stack web application");
    let prompt = build_generation_prompt(&plan, summary, None);

    let generated_files =
        super::llm_codegen::generate_app_files(&state, &prompt, Some(&project_id))
            .await
            .map_err(ApiError::Internal)?;

    info!(
        project = %project_id,
        file_count = generated_files.len(),
        "LLM generated files, writing to disk"
    );

    // Step 3: Write files + create DB entries
    let db = state.db.lock().await;
    let materializer = CodeGenMaterializer::new(&db);
    let result = materializer
        .generate_from_llm_output(
            &project_id,
            &output_dir,
            &plan,
            &project_data_db,
            &generated_files,
        )
        .map_err(|e| ApiError::Internal(format!("Codegen write failed: {e}")))?;

    Ok(Json(serde_json::to_value(result)?))
}
